"""Audited files allowed in demo and packaged application distributions."""
from __future__ import annotations


DEMO_ROOT_FILES = (
    "DEMO.md",
    "README.md",
    "THIRD_PARTY_NOTICES.md",
    "build_demo_bundle.py",
    "build_maisoku_template.py",
    "demo_walkthrough.py",
    "distribution_manifest.py",
    "install_ainote.py",
    "record_local_web_macos.py",
    "requirements.txt",
    "requirements-office.txt",
    "structured_unittest.py",
    "seed_demo.py",
    "serve.py",
    "start_ainote.py",
    "start_ainote.sh",
)

PUBLIC_DOCUMENT_FILES = (
    "docs/ARCHITECTURE.md",
    "docs/書類エンジン.md",
)

HUB_CORE_FILES = (
    "hub_core/__init__.py",
    "hub_core/access.py",
    "hub_core/activity_report.py",
    "hub_core/ad_copy.py",
    "hub_core/ad_rules.py",
    "hub_core/analytics.py",
    "hub_core/audit.py",
    "hub_core/auth.py",
    "hub_core/backup.py",
    "hub_core/branding.py",
    "hub_core/chat_bridge.py",
    "hub_core/chat_history.py",
    "hub_core/chat_llm.py",
    "hub_core/connections.py",
    "hub_core/contract.py",
    "hub_core/deal_taxonomy.py",
    "hub_core/docgen.py",
    "hub_core/documents.py",
    "hub_core/esign.py",
    "hub_core/esign_provider.py",
    "hub_core/extract.py",
    "hub_core/fax.py",
    "hub_core/files.py",
    "hub_core/flex_card.py",
    "hub_core/followup.py",
    "hub_core/hazard_links.py",
    "hub_core/ics.py",
    "hub_core/inbox.py",
    "hub_core/it_juusetsu.py",
    "hub_core/juusetsu_draft.py",
    "hub_core/keisan.py",
    "hub_core/labels.py",
    "hub_core/liff_export.py",
    "hub_core/line.py",
    "hub_core/line_webhook.py",
    "hub_core/local_ocr.py",
    "hub_core/macos_ocr.py",
    "hub_core/madori.py",
    "hub_core/maisoku.py",
    "hub_core/matching.py",
    "hub_core/metering.py",
    "hub_core/migrate.py",
    "hub_core/obi.py",
    "hub_core/ocr.py",
    "hub_core/ocr_geom.py",
    "hub_core/ocr_structure.py",
    "hub_core/operations.py",
    "hub_core/op_scope.py",
    "hub_core/pii.py",
    "hub_core/portal.py",
    "hub_core/portal_export.py",
    "hub_core/property_info.py",
    "hub_core/proposal.py",
    "hub_core/provenance.py",
    "hub_core/prs.py",
    "hub_core/prs_juusetsu.py",
    "hub_core/reins.py",
    "hub_core/schema_cols.py",
    "hub_core/screening.py",
    "hub_core/search.py",
    "hub_core/sender.py",
    "hub_core/sovereignty.py",
    "hub_core/store.py",
    "hub_core/telephony.py",
    "hub_core/templates_lib.py",
    "hub_core/ui.py",
    "hub_core/vault.py",
    "hub_core/viewlog.py",
    "hub_core/views.py",
    "hub_core/windows_ocr.py",
    "hub_core/worklist.py",
    "hub_core/zengin.py",
    "hub_core/zoning.py",
)

# (source, destination) pairs consumed directly by PyInstaller.
PYINSTALLER_DATAS = (
    ("THIRD_PARTY_NOTICES.md", "."),
    ("hub_core/templates/maisoku/clean-ui.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/dense-pro.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/editorial.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/shuueki.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/standard.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/survey.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/v2-photo.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/v2-sumi.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/maisoku/v2-tate.html", "hub_core/templates/maisoku"),
    ("hub_core/templates/office/maisoku_a_standard_landscape.xlsx", "hub_core/templates/office"),
    ("hub_core/templates/office/maisoku_b_buyer_portrait.xlsx", "hub_core/templates/office"),
    ("hub_core/templates/office/maisoku_c_fax_mono.xlsx", "hub_core/templates/office"),
    ("hub_core/templates/office/juusetsu_schema.json", "hub_core/templates/office"),
    ("packaging/ocr-smoke-fixture.pdf", "packaging"),
    ("packaging/vision_ocr.swift", "packaging"),
    ("schema/sql/001_init.sql", "schema/sql"),
    ("schema/sql/002_business_os.sql", "schema/sql"),
    ("schema/sql/003_vault.sql", "schema/sql"),
    ("schema/sql/004_ledger.sql", "schema/sql"),
    ("schema/sql/005_lost_match.sql", "schema/sql"),
    ("schemas/hub_event.schema.json", "schemas"),
    ("schemas/portal_lead.schema.json", "schemas"),
    ("schemas/task.schema.json", "schemas"),
    ("licenses/cryptography/LICENSE", "licenses/cryptography"),
    ("licenses/cryptography/LICENSE.APACHE", "licenses/cryptography"),
    ("licenses/cryptography/LICENSE.BSD", "licenses/cryptography"),
    ("licenses/cffi/LICENSE", "licenses/cffi"),
    ("licenses/cffi/AUTHORS", "licenses/cffi"),
    ("licenses/pycparser/LICENSE", "licenses/pycparser"),
    ("licenses/openpyxl/LICENSE", "licenses/openpyxl"),
    ("licenses/Pillow/LICENSE", "licenses/Pillow"),
    ("licenses/python-docx/LICENSE", "licenses/python-docx"),
    ("licenses/lxml/LICENSE.txt", "licenses/lxml"),
    ("licenses/lxml/LICENSES.txt", "licenses/lxml"),
    ("licenses/et-xmlfile/LICENCE.rst", "licenses/et-xmlfile"),
    ("licenses/et-xmlfile/LICENCE.python", "licenses/et-xmlfile"),
    ("licenses/et-xmlfile/AUTHORS.txt", "licenses/et-xmlfile"),
    ("licenses/typing-extensions/LICENSE", "licenses/typing-extensions"),
    ("licenses/python/LICENSE.txt", "licenses/python"),
)

DEMO_FILES = tuple(dict.fromkeys(
    DEMO_ROOT_FILES + HUB_CORE_FILES + PUBLIC_DOCUMENT_FILES + tuple(
        source for source, _destination in PYINSTALLER_DATAS
    )
))
